# Define the name of the workflow
name: snyk-server

# Define variables
env:
  DOCKER_REGISTRY: registry.ncats.nih.gov:5000
  IMAGE_NAME: rampdb-api

# Define when the workflow should be triggered (on push to a specific branch and pull requests to the master branch)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Define the jobs that will be executed as part of the workflow 
jobs:
  # Job to build and push the ZAP Docker image to Docker Hub
  Snyk-Docker-Image:
    runs-on:
      group: ncats-onprem-internal-runners
    permissions:
      actions: read
      contents: read
      security-events: write
      issues: write
    
    outputs:
      build_version: ${{ steps.get_build_version.outputs.build_version }}
      RUNNER: ${{ runner.name }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Generate Build Version Number
      - name: Generate Build Version Number
        id: GET_BUILD_VERSION
        run: |
          # Get the last recorded date from the environment variable
          LAST_DATE=$(date -d "$LAST_BUILD_DATE" +'%Y-%m-%d' 2>/dev/null || echo "")
      
          # Get the current date
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "Last recorded date: $LAST_DATE"
          echo "Current date: $CURRENT_DATE"
      
          # Check if it's a new day
          if [ "$LAST_DATE" != "$CURRENT_DATE" ]; then
            # Reset BUILDS_TODAY to 0 for the new day
            BUILDS_TODAY=0
            echo "Resetting BUILDS_TODAY to 0 for the new day"
          else
            # Calculate the number of builds today
            BUILDS_TODAY=$(seq -f v$GITHUB_RUN_NUMBER.%g $(($GITHUB_RUN_NUMBER - 1)) | wc -l)
            echo "Incrementing BUILDS_TODAY"
          fi
    
          # Store the current date for the next run
          echo "LAST_BUILD_DATE=$CURRENT_DATE" >> $GITHUB_ENV
        
          # Generate the build version with the number of builds today
          BUILD_VERSION_GENERATED=$(date +v%Y.%m%d.$BUILDS_TODAY)
          echo "Generated Build Version: $BUILD_VERSION_GENERATED"
          echo "BUILD_VERSION=$BUILD_VERSION_GENERATED" >> $GITHUB_ENV
          echo "BUILD=true" >> $GITHUB_ENV
          echo "::set-output name=build_version::$BUILD_VERSION_GENERATED"
    
      # Step 4: Build a Docker image
      - name: Build a Docker image
        run: docker build --no-cache -f ./apps/ramp-client/Dockerfile --build-arg BUILD_VERSION=$BUILD_VERSION -t $DOCKER_REGISTRY/$IMAGE_NAME:$BUILD_VERSION .

       # Step 5: Run Snyk to check Docker image for vulnerabilities
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        id: docker-image-scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_CLI }}
        with:
          command: monitor
          image: $DOCKER_REGISTRY/$IMAGE_NAME:$BUILD_VERSION
          args: --sarif-file-output=snyk.sarif --file=./apps/ramp-client/Dockerfile
